/// Flutter icons CustomIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData arrowDown = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData events = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData menu = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData places = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData qrCode = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData showcases = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData user = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData wallet = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData apple = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData frend = IconData(0xe80c, fontFamily: _kFontFam);
}
