// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQMJmPT9B37JgQYJlPD-iAp4oy1loqRaI',
    appId: '1:520847529073:web:d5772c3276cb0286beb7d0',
    messagingSenderId: '520847529073',
    projectId: 'localyft-app',
    authDomain: 'localyft-app.firebaseapp.com',
    storageBucket: 'localyft-app.appspot.com',
    measurementId: 'G-SRY6QMQQFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK-x84gCqnCnXydvdlo7ypQfPluyb80v4',
    appId: '1:520847529073:android:b90890dcc14bd8fbbeb7d0',
    messagingSenderId: '520847529073',
    projectId: 'localyft-app',
    storageBucket: 'localyft-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWbL5Pri1lSvQZ5KCwu8Pl8tQjps2l0Q8',
    appId: '1:520847529073:ios:d7b230a8650f2feabeb7d0',
    messagingSenderId: '520847529073',
    projectId: 'localyft-app',
    storageBucket: 'localyft-app.appspot.com',
    iosBundleId: 'com.example.localyft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWbL5Pri1lSvQZ5KCwu8Pl8tQjps2l0Q8',
    appId: '1:520847529073:ios:fda54fda7803d808beb7d0',
    messagingSenderId: '520847529073',
    projectId: 'localyft-app',
    storageBucket: 'localyft-app.appspot.com',
    iosBundleId: 'com.example.localyft.RunnerTests',
  );
}
